# This workflow will do a clean install of node dependencies, build the source code and push the binaries to the deployment branch.
name: Continuous Delivery

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: yarn install
            - run: yarn run build
            - uses: actions/upload-artifact@v3
            with:
            name: my-artifact
            path: build
